from django.core.management.base import BaseCommand
from game.models import Mission

MISSIONS = [
{'phase': 1, 'order': 1, 'title': 'Ato 1 — Perdidos na Escuridão', 'story': 'Houve um apagão rápido. Entramos no terminal e não sabemos em qual sala da fábrica estamos.', 'question': 'Como saber onde estamos no Linux?', 'expected_answer': 'pwd', 'aliases': 'PWD', 'command_example': 'pwd', 'explanation': 'O pwd significa print working directory. Ele mostra o diretório atual, funcionando como um GPS dentro da fábrica Linux.'},
{'phase': 1, 'order': 2, 'title': 'Ato 2 — Sala de Controle', 'story': 'Estamos no /home, mas precisamos chegar à sala das configurações.', 'question': 'Qual comando usamos para andar entre diretórios?', 'expected_answer': 'cd', 'aliases': 'cd /etc', 'command_example': 'cd /etc', 'explanation': 'O cd muda o diretório atual. Usamos cd /etc para entrar na sala de configurações da fábrica.'},
{'phase': 1, 'order': 3, 'title': 'Ato 3 — A Sala dos Painéis', 'story': 'Precisamos acessar a área onde ficam arquivos de configuração.', 'question': 'Qual diretório representa a sala de configurações?', 'expected_answer': '/etc', 'aliases': 'etc', 'command_example': 'cd /etc', 'explanation': 'O /etc guarda vários arquivos de configuração do sistema e de serviços.'},
{'phase': 1, 'order': 4, 'title': 'Ato 4 — Investigando os Diários', 'story': 'O suporte quer olhar registros recentes.', 'question': 'Em qual diretório normalmente ficam os logs do sistema?', 'expected_answer': '/var/log', 'aliases': '/var,var/log', 'command_example': 'cd /var/log', 'explanation': 'Os logs costumam ficar em /var/log. A pasta /var armazena dados variáveis.'},
{'phase': 1, 'order': 5, 'title': 'Ato 5 — Lendo só o Final', 'story': 'O arquivo de log é enorme e queremos apenas as últimas linhas.', 'question': 'Qual comando mostra o final de um arquivo?', 'expected_answer': 'tail', 'aliases': 'tail -f', 'command_example': 'tail /var/log/messages', 'explanation': 'O tail mostra as últimas linhas de um arquivo. É muito usado para analisar logs recentes.'},
{'phase': 1, 'order': 6, 'title': 'Ato 6 — O Papel em Branco', 'story': 'Precisamos criar um arquivo vazio para receber uma nova regra.', 'question': 'Qual comando cria um arquivo vazio?', 'expected_answer': 'touch', 'aliases': 'TOUCH', 'command_example': 'touch regra.conf', 'explanation': 'O touch pode criar um arquivo vazio e também atualizar a data de modificação.'},
{'phase': 1, 'order': 7, 'title': 'Ato 7 — Acesso Negado', 'story': 'O sistema bloqueou uma alteração por falta de permissão.', 'question': 'Quem é o super usuário com chave-mestra no Linux?', 'expected_answer': 'root', 'aliases': 'sudo,super usuario,superusuário,super chefe', 'command_example': 'sudo comando', 'explanation': 'O root é o super usuário do Linux. O sudo permite executar tarefas administrativas quando autorizado.'},
{'phase': 1, 'order': 8, 'title': 'Ato 8 — Lousa de Rascunhos', 'story': 'Há um arquivo temporário jogado na lousa de rascunhos.', 'question': 'Qual diretório é usado para arquivos temporários?', 'expected_answer': '/tmp', 'aliases': 'tmp', 'command_example': 'cd /tmp', 'explanation': 'O /tmp é usado para arquivos temporários e não deve guardar documentos importantes.'},
{'phase': 1, 'order': 9, 'title': 'Ato 9 — O Triturador', 'story': 'Precisamos apagar um arquivo temporário.', 'question': 'Qual comando remove arquivos?', 'expected_answer': 'rm', 'aliases': 'rm arquivo.txt', 'command_example': 'rm arquivo.txt', 'explanation': 'O rm remove arquivos. Deve ser usado com cuidado, pois nem sempre há lixeira ou desfazer.'},
{'phase': 1, 'order': 10, 'title': 'Ato 10 — Tela Limpa', 'story': 'O terminal ficou cheio de letras e comandos antigos.', 'question': 'Qual comando limpa a tela do terminal?', 'expected_answer': 'clear', 'aliases': 'CTRL+L,ctrl+l', 'command_example': 'clear', 'explanation': 'O clear limpa visualmente a tela do terminal, ajudando a organizar o trabalho.'},
{'phase': 2, 'order': 1, 'title': 'Ato 1 — A Contratação do Novo Herói', 'story': 'O RH aprovou a contratação do técnico Carlos. O sistema precisa imprimir o crachá dele.', 'question': 'Qual comando usamos para criar esse novo usuário no terminal?', 'expected_answer': 'useradd', 'aliases': 'useradd carlos,adduser,adduser carlos', 'command_example': 'sudo useradd carlos', 'explanation': 'O useradd cria um novo usuário no Linux. Na metáfora, emite o crachá e registra Carlos na fábrica.'},
{'phase': 2, 'order': 2, 'title': 'Ato 2 — O Segredo do Cadeado', 'story': 'Carlos existe, mas ainda não tem senha para passar pela catraca.', 'question': 'Qual comando cria ou troca a senha de um usuário?', 'expected_answer': 'passwd', 'aliases': 'passwd carlos', 'command_example': 'sudo passwd carlos', 'explanation': 'O passwd é o chaveiro do Linux. Ele define ou altera a senha de um usuário.'},
{'phase': 2, 'order': 3, 'title': 'Ato 3 — Criando o Departamento', 'story': 'Carlos precisa trabalhar na equipe de monitoramento, mas o departamento ainda não existe.', 'question': 'Qual comando cria um novo grupo no Linux?', 'expected_answer': 'groupadd', 'aliases': 'groupadd monitoramento', 'command_example': 'sudo groupadd monitoramento', 'explanation': 'O groupadd cria um grupo. Grupo é como um departamento: RH, Suporte ou Monitoramento.'},
{'phase': 2, 'order': 4, 'title': 'Ato 4 — Vestindo a Camisa da Equipe', 'story': 'O grupo monitoramento foi criado. Agora Carlos precisa entrar nessa equipe.', 'question': 'Qual comando modifica o usuário para adicioná-lo a um grupo?', 'expected_answer': 'usermod', 'aliases': 'usermod -aG monitoramento carlos,usermod -a -G monitoramento carlos', 'command_example': 'sudo usermod -aG monitoramento carlos', 'explanation': 'O usermod altera propriedades de um usuário. Com -aG, adicionamos o usuário a um grupo sem remover os grupos atuais.'},
{'phase': 2, 'order': 5, 'title': 'Ato 5 — Raio-X do Crachá', 'story': 'A auditoria quer verificar UID, GID e grupos de Carlos.', 'question': 'Qual comando mostra o raio-X completo do usuário?', 'expected_answer': 'id', 'aliases': 'id carlos', 'command_example': 'id carlos', 'explanation': 'O id mostra UID, GID e grupos de um usuário. É ótimo para auditoria rápida de permissões.'},
{'phase': 2, 'order': 6, 'title': 'Ato 6 — Lista de Equipes', 'story': 'O instrutor quer apenas saber de quais equipes Carlos participa.', 'question': 'Qual comando lista os grupos de um usuário de forma simples?', 'expected_answer': 'groups', 'aliases': 'groups carlos', 'command_example': 'groups carlos', 'explanation': 'O groups mostra os grupos aos quais um usuário pertence.'},
{'phase': 2, 'order': 7, 'title': 'Ato 7 — A Escritura da Pasta', 'story': 'Uma pasta de scripts pertence a outra pessoa e precisa passar para Carlos.', 'question': 'Qual comando muda o dono de um arquivo ou pasta?', 'expected_answer': 'chown', 'aliases': 'chown carlos,chown carlos scripts', 'command_example': 'sudo chown carlos scripts/', 'explanation': 'O chown muda o dono de arquivos e pastas. É a escritura da fábrica.'},
{'phase': 2, 'order': 8, 'title': 'Ato 8 — O Botão Verde', 'story': 'O script iniciar_rede.sh não tem permissão de execução.', 'question': 'Qual comando altera permissões e pode adicionar o +x?', 'expected_answer': 'chmod', 'aliases': 'chmod +x,chmod +x iniciar_rede.sh', 'command_example': 'chmod +x iniciar_rede.sh', 'explanation': 'O chmod é o chaveiro mágico das permissões. Com +x, adicionamos execução ao arquivo.'},
{'phase': 2, 'order': 9, 'title': 'Ato 9 — O Shopping Debian/Ubuntu', 'story': 'Em Ubuntu, precisamos atualizar a lista de produtos antes de instalar pacotes.', 'question': 'Qual comando atualiza a lista de pacotes na família Debian/Ubuntu?', 'expected_answer': 'apt update', 'aliases': 'apt-get update,sudo apt update', 'command_example': 'sudo apt update', 'explanation': 'O apt update atualiza o catálogo local de pacotes disponíveis nos repositórios.'},
{'phase': 2, 'order': 10, 'title': 'Ato 10 — O Caminhão Blindado do Zabbix', 'story': 'Em Rocky/AlmaLinux/Red Hat, Carlos precisa instalar o Zabbix.', 'question': 'Qual comando usamos nessa família para instalar o Zabbix?', 'expected_answer': 'dnf install zabbix', 'aliases': 'sudo dnf install zabbix,dnf install zabbix -y,dnf install zabbix-server', 'command_example': 'sudo dnf install zabbix', 'explanation': 'Na família Rocky, AlmaLinux e Red Hat, o gerenciador moderno é o dnf. Usamos dnf install para instalar pacotes.'},
{'phase': 3, 'order': 1, 'title': 'Ato 1 — Acordando o Guarda de Segurança', 'story': 'O Zabbix foi instalado, mas o guarda de segurança ainda está dormindo no posto. Precisamos iniciar o serviço imediatamente.', 'question': 'Qual comando usamos para mandar um serviço iniciar agora?', 'expected_answer': 'systemctl start', 'aliases': 'systemctl start zabbix,systemctl start zabbix-server,sudo systemctl start zabbix,sudo systemctl start zabbix-server', 'command_example': 'sudo systemctl start zabbix', 'explanation': 'O systemctl start manda um serviço começar a trabalhar imediatamente. É como chamar o guarda pelo rádio e ordenar que assuma o posto.'},
{'phase': 3, 'order': 2, 'title': 'Ato 2 — Conferindo o Guarda', 'story': 'O serviço foi iniciado, mas precisamos confirmar se o guarda realmente está trabalhando ou se deu erro.', 'question': 'Qual comando perguntamos ao systemctl para verificar a situação de um serviço?', 'expected_answer': 'systemctl status', 'aliases': 'systemctl status zabbix,systemctl status zabbix-server,sudo systemctl status zabbix', 'command_example': 'systemctl status zabbix', 'explanation': 'O systemctl status mostra o estado do serviço: se está ativo, parado, com erro ou registrando alguma falha.'},
{'phase': 3, 'order': 3, 'title': 'Ato 3 — Ligando Automaticamente Amanhã', 'story': 'O Zabbix funciona agora, mas precisa acordar sozinho sempre que a fábrica reiniciar.', 'question': 'Qual comando habilita um serviço para iniciar automaticamente no boot?', 'expected_answer': 'systemctl enable', 'aliases': 'systemctl enable zabbix,systemctl enable zabbix-server,sudo systemctl enable zabbix', 'command_example': 'sudo systemctl enable zabbix', 'explanation': 'O systemctl enable cria a regra para o serviço iniciar automaticamente quando o sistema ligar.'},
{'phase': 3, 'order': 4, 'title': 'Ato 4 — A Câmera Fotográfica', 'story': 'A fábrica está estranha e precisamos tirar uma foto instantânea dos operários em execução.', 'question': 'Qual comando tira uma foto dos processos em execução?', 'expected_answer': 'ps', 'aliases': 'ps aux,ps -ef', 'command_example': 'ps aux', 'explanation': 'O ps mostra processos em execução naquele momento. É como uma câmera fotográfica tirando uma Polaroid da fábrica.'},
{'phase': 3, 'order': 5, 'title': 'Ato 5 — A Câmera de Segurança Ao Vivo', 'story': 'O servidor está lento e precisamos ver ao vivo quem está consumindo mais CPU e memória.', 'question': 'Qual comando mostra processos em tempo real?', 'expected_answer': 'top', 'aliases': 'htop', 'command_example': 'top', 'explanation': 'O top mostra uma visão dinâmica dos processos, consumo de CPU, memória e carga do sistema. É a câmera de segurança ao vivo.'},
{'phase': 3, 'order': 6, 'title': 'Ato 6 — O Operário Enlouquecido', 'story': 'Um processo travou e está consumindo energia demais. Sabemos o PID do processo e precisamos encerrá-lo.', 'question': 'Qual comando encerra um processo pelo PID?', 'expected_answer': 'kill', 'aliases': 'kill -9,kill 1234,kill -9 1234', 'command_example': 'kill 1234', 'explanation': 'O kill envia um sinal para encerrar um processo usando o PID, que funciona como o crachá do operário.'},
{'phase': 3, 'order': 7, 'title': 'Ato 7 — O Jogo de Marco Polo', 'story': 'O painel está amarelo. Precisamos testar se a estrada até outro servidor está respondendo.', 'question': 'Qual ferramenta usamos para testar conectividade com resposta Pong?', 'expected_answer': 'ping', 'aliases': 'ping 10.18.1.5', 'command_example': 'ping 10.18.1.5', 'explanation': 'O ping envia pacotes para outro endereço e espera resposta. Se houver resposta, a comunicação básica entre os pontos está funcionando.'},
{'phase': 3, 'order': 8, 'title': 'Ato 8 — Qual é o Endereço da Fábrica?', 'story': 'Precisamos descobrir qual IP a máquina recebeu agora na rede interna.', 'question': 'Qual comando mostra os endereços IP da máquina?', 'expected_answer': 'ip addr', 'aliases': 'ip a,ip address', 'command_example': 'ip addr', 'explanation': 'O ip addr mostra os endereços IP configurados nas interfaces da máquina, como a identidade de rede da fábrica.'},
{'phase': 3, 'order': 9, 'title': 'Ato 9 — O Túnel Secreto', 'story': 'A estrada funciona, mas precisamos assumir o terminal de um servidor remoto de forma segura.', 'question': 'Qual ferramenta abre um acesso remoto seguro pelo terminal?', 'expected_answer': 'ssh', 'aliases': 'ssh usuario@servidor,ssh carlos@10.18.1.5', 'command_example': 'ssh usuario@servidor', 'explanation': 'O SSH cria um túnel seguro para você operar o terminal de outra máquina como se estivesse ao lado dela.'},
{'phase': 3, 'order': 10, 'title': 'Ato 10 — A Cápsula de Transporte', 'story': 'Falta enviar o arquivo reparo_urgente.sh para o servidor remoto com segurança.', 'question': 'Qual ferramenta copia arquivos de forma segura entre máquinas?', 'expected_answer': 'scp', 'aliases': 'scp reparo_urgente.sh usuario@servidor:/tmp,scp arquivo usuario@servidor:/pasta', 'command_example': 'scp reparo_urgente.sh usuario@servidor:/tmp', 'explanation': 'O scp usa o túnel seguro do SSH para copiar arquivos entre computadores de forma criptografada.'},
{'phase': 4, 'order': 1, 'title': 'Ato 1 — O Alarme Toca', 'story': 'O Zabbix ficou vermelho e o servidor da AWS parou de responder. Precisamos ver há quanto tempo a máquina está ligada sem descansar.', 'question': 'Qual comando mostra o tempo de atividade da máquina?', 'expected_answer': 'uptime', 'aliases': 'UPTIME', 'command_example': 'uptime', 'explanation': 'O uptime é o relógio de ponto da fábrica. Ele mostra há quanto tempo o sistema está ligado, a quantidade de usuários e a carga média.'},
{'phase': 4, 'order': 2, 'title': 'Ato 2 — A Câmera da Lentidão', 'story': 'A máquina está engasgando e precisamos ver ao vivo quem está consumindo CPU e memória.', 'question': 'Qual comando de três letras abre a câmera de segurança ao vivo dos processos?', 'expected_answer': 'top', 'aliases': 'TOP', 'command_example': 'top', 'explanation': 'O top mostra processos em tempo real e ajuda a identificar consumo alto de CPU ou memória.'},
{'phase': 4, 'order': 3, 'title': 'Ato 3 — O Espaço nas Mesas', 'story': 'A CPU parece normal, mas queremos saber rapidamente quanta memória RAM está livre de forma humana.', 'question': 'Qual comando mostra a memória em formato humano?', 'expected_answer': 'free -h', 'aliases': 'free,free -m', 'command_example': 'free -h', 'explanation': 'O free -h mostra memória total, usada e livre. O -h significa human-readable, exibindo valores em MB ou GB.'},
{'phase': 4, 'order': 4, 'title': 'Ato 4 — O Mapa dos Galpões', 'story': 'A fábrica pode ter parado por falta de espaço no estoque. Precisamos ver o uso do disco inteiro em formato humano.', 'question': 'Qual comando mostra o uso dos discos em formato humano?', 'expected_answer': 'df -h', 'aliases': 'df,df -H', 'command_example': 'df -h', 'explanation': 'O df -h mostra o uso das partições e sistemas de arquivos. É a visão geral do almoxarifado da máquina.'},
{'phase': 4, 'order': 5, 'title': 'Ato 5 — A Balança de Caixas', 'story': 'O disco está cheio. Agora precisamos pesar uma pasta específica para descobrir quem ocupa espaço demais.', 'question': 'Qual comando pesa uma pasta específica de forma resumida e humana?', 'expected_answer': 'du -sh', 'aliases': 'du -sh /tmp,du -sch', 'command_example': 'du -sh /tmp', 'explanation': 'O du -sh mostra o tamanho resumido de uma pasta ou arquivo. É a balança usada para encontrar caixas gigantes no almoxarifado.'},
{'phase': 4, 'order': 6, 'title': 'Ato 6 — A Sala dos Diários', 'story': 'A equipe precisa ir para a sala onde ficam os registros tradicionais do sistema.', 'question': 'Qual diretório guarda a maior parte dos logs do Linux?', 'expected_answer': '/var/log', 'aliases': 'var/log,/var', 'command_example': 'cd /var/log', 'explanation': 'O /var/log é a sala dos diários do Linux. Ali ficam muitos registros de sistema, serviços e aplicações.'},
{'phase': 4, 'order': 7, 'title': 'Ato 7 — Diário ao Vivo', 'story': 'O chefe quer olhar um arquivo de log sendo escrito ao vivo, linha por linha, usando a técnica do rabo do documento.', 'question': 'Qual comando acompanha o final de um arquivo em tempo real?', 'expected_answer': 'tail -f', 'aliases': 'tail -f arquivo.log,tail -f /var/log/messages', 'command_example': 'tail -f /var/log/messages', 'explanation': 'O tail -f mantém o arquivo aberto e acompanha novas linhas em tempo real. O -f significa follow, ou seguir.'},
{'phase': 4, 'order': 8, 'title': 'Ato 8 — O Diário Digital dos Guardas', 'story': 'Um serviço falhou e precisamos abrir o final do diário digital com explicações extras do erro.', 'question': 'Qual comando mostra o final do journal com detalhes extras de erro?', 'expected_answer': 'journalctl -xe', 'aliases': 'sudo journalctl -xe,journalctl -e -x', 'command_example': 'journalctl -xe', 'explanation': 'O journalctl -xe mostra as entradas recentes do journal e inclui detalhes extras para ajudar na investigação do erro.'},
{'phase': 4, 'order': 9, 'title': 'Ato 9 — Filtrando o Guarda Certo', 'story': 'Não queremos ler todos os diários. Queremos apenas as anotações de um serviço específico.', 'question': 'Qual comando filtra logs de um serviço específico no journalctl?', 'expected_answer': 'journalctl -u', 'aliases': 'journalctl -u zabbix,journalctl -u zabbix-server,sudo journalctl -u zabbix', 'command_example': 'journalctl -u zabbix', 'explanation': 'O journalctl -u filtra os logs por unidade/serviço do systemd. Assim você vê apenas o diário daquele guarda.'},
{'phase': 4, 'order': 10, 'title': 'Ato 10 — Recomeçando o Turno', 'story': 'O disco foi limpo, mas o serviço de monitoramento ainda está fora do ar. Precisamos mandar o guarda reiniciar o turno do zero.', 'question': 'Qual comando reinicia um serviço pelo systemctl?', 'expected_answer': 'systemctl restart', 'aliases': 'systemctl restart zabbix,systemctl restart zabbix-server,sudo systemctl restart zabbix', 'command_example': 'sudo systemctl restart zabbix', 'explanation': 'O systemctl restart para e inicia o serviço novamente. É útil quando uma aplicação travou ou precisa recarregar após correção.'}
]

class Command(BaseCommand):
    help = 'Popula o banco com as missões iniciais das fases do jogo Detetive Linux.'
    def handle(self, *args, **options):
        created = updated = 0
        for data in MISSIONS:
            obj, was_created = Mission.objects.update_or_create(phase=data['phase'], order=data['order'], defaults=data)
            created += int(was_created); updated += int(not was_created)
        self.stdout.write(self.style.SUCCESS(f'Missões carregadas. Criadas: {created}. Atualizadas: {updated}. Total: {Mission.objects.count()}'))
